Bento4 MP4 SDK: AP4_List< T >::Item::Operator Class Reference
AP4_List< T >::Item::Operator Class Reference
#include <Ap4List.h>
Public Member Functions
virtual ~Operator ()
virtual AP4_Result Action (T *data) const =0
Detailed Description
template<typename T>
class AP4_List< T >::Item::Operator
Definition at line 55 of file Ap4List.h.
Constructor & Destructor Documentation
template<typename T> virtual AP4_List< T >::Item::Operator::~Operator () [inline, virtual]
Definition at line 59 of file Ap4List.h.
Member Function Documentation
template<typename T> virtual AP4_Result AP4_List< T >::Item::Operator::Action (T * data) const [pure virtual]
Referenced by AP4_List< T >::Apply(), AP4_List< T >::ApplyUntilFailure(), AP4_List< T >::ApplyUntilSuccess(), and AP4_List< T >::ReverseApply().
The documentation for this class was generated from the following file:
Ap4List.h